[package]
name = "asteroids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flax = { path = "../" }
macroquad = "0.3"
glam = { version = "0.21", features = ["rand", "serde"] }
rand = "0.8.5"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tracing-tree = "0.2.1"
color-eyre = "0.6"
itertools = "0.10"
flume = "0.10.14"
atomic_refcell = "0.1.8"
